### ISSUE TITLE
Not able to make it work... how to do it?

### ISSUE THREAD

**Issue by caballerofelipe** [image-charts/mjml-chart#4]
Hi,

I read the docs but haven't been able to make it work.

I installed it, I added the code to my mjml file ant then when trying to compile it it throws an error.
```bash
# Install mjml
npm init -y && npm install mjml
# Install  mjml-chart
npm install mjml-chart@5 --save
# run
mjml -w mail.mjml
```

I get the following error:
```
[ { line: 40,
    message: 'Element mj-chart doesn\'t exist or is not registered',
    tagName: 'mj-chart',
    formattedMessage:
     'Line 40 of {PATH}/mail.mjml (mj-chart) — Element mj-chart doesn\'t exist or is not registered' } ] 'Line 40 of {PATH}/mail.mjml (mj-chart) — Element mj-chart doesn\'t exist or is not registered'
{PATH}/
```

Am I missing something else to install?

**Comment by FGRibreau** [comment]
Hello @caballerofelipe,

Did you ask on mjml slack? https://slack.mjml.io/

**Comment by ecarlin** [comment]
@caballerofelipe did you ever figure out? I'm getting the exact same error. Anyone else monitoring this that can answer?

**Comment by caballerofelipe** [comment]
@ecarlin No, I couldn't make it work and then I stopped trying... sorry...

**Comment by ecarlin** [comment]
@caballerofelipe Thanks. FYI, I jumped on mjml slack and they helped identify the problem. You need to setup a .mjmlconfig file that tells mjml about 3rd party components to pull-in. It's not described in the mjml-chart README but is on the mjml docs page [here (https://mjml.io/documentation/#community-components) (which I originally missed).

**Comment by FGRibreau** [comment]
For futur referance: 

> To use a community component, proceed as follows: - Install MJML locally with npm install mjml in a folder - Install the community component with npm install {component-name} in the same folder - Create a .mjmlconfig file in the same folder with:

```
{
  "packages": [
    "component-name/path-to-js-file"
  ]
}
```

> Finally, you can now use the component in a MJML file, for example index.mjml, and run MJML locally in your terminal (make sure to be in the folder where you installed MJML and the community component): ./node_modules/.bin/mjml index.mjml.
