### ISSUE TITLE
Receiving Error: `Error when registering custom component`

### ISSUE THREAD

**Issue by sjones6** [image-charts/mjml-chart#66]
```
Error when registering custom component : node_modules/mjml-chart/lib/index.js TypeError: Cannot read property 'BodyComponent' of undefined
    at Object.get [as BodyComponent] (node_modules/mjml-core/lib/index.js:50:29)

```
This seems to happen on initialization, even those the component seems to work properly and the chart is embedded, so I'm not sure if this error is causing any errant behavior but it's noisy in the console.

System Info:
node 10.17.0
mjml 4.6.3
mjml-chart 5.3.2

MacOS Mojave

**Comment by FGRibreau** [comment]
poke @btourman

**Comment by btourman** [comment]
Hi @sjones6,
Sorry for the delay. 
Could you send me the code to reproduce this behavior ?

**Comment by btourman** [comment]
Hi,

This issue is no longer present with mjml 4.7.1 and mjml-chart 5.6.0
