### ISSUE TITLE
MJML Error: Element mj-chart doesn't exist or is not registered. 

### ISSUE THREAD

**Issue by sebringrose** [image-charts/mjml-chart#72]
Upon inspection of my local npm modules I can see that mjml-chart/ib/index.js is empty. Seems that the build script is failing in CI? Possibly resolvable within ci.sh file but I am at a loss trying to understand what is going on in there tbh. Any pointers? For now will try downgrading versions.

**Comment by btourman** [comment]
Hi @sebringrose,
😮 It's not a very good news.
I solve this as quickly as possible

**Comment by btourman** [comment]
It must be good now.
We used babel command but since version 6, it's directly included in babel-cli.
So I just removed babel in devDependencies
